project:
  type: website
  output-dir: web_output

website:
  title: "Yuxuan Chen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: About Me 
        menu:
          - href: about.qmd
            text: Profile 
          - href: resume.qmd
            text: Résumé Download
          - href: Resume_Chinese.qmd
            text: 简历下载
      - href: projects.qmd
        text: Prjects
      - href: contact.qmd
        text: Contact Me


    tools:
      - icon: github
        menu:
          - text: Home Page
            href:  https://github.com/CYXNBNBNB
          - text: Source Code
            href:  https://github.com/CYXNBNBNB/cyxnbnbnb.github.io




#此为统一为所有设置格式
#format:
#  html:
#    theme:
#      - cosmo
#      - brand
#    css: styles.css
#    toc: true




