project:
  type: website
  output-dir: web_output

website:
  title: "Yuxuan Chen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: documents.qmd
        text: Documents
      - href: resume.qmd
        text: Résumé

    tools:
      - icon: github
        menu:
          - text: Home Page
            href:  https://github.com/CYXNBNBNB
          - text: Source Code
            href:  https://github.com/CYXNBNBNB/cyxnbnbnb.github.io




#此为统一为所有设置格式
#format:
#  html:
#    theme:
#      - cosmo
#      - brand
#    css: styles.css
#    toc: true




