---
format: 
  pdf: 
    documentclass: article
    geometry:
      - top=10mm
      - left=15mm
      - right=15mm
      - bottom=5mm
      - heightrounded
    fontfamily: libertine
    colorlinks: true
    fontsize: '16'
    include-in-header: 
      text: |
        \usepackage{multicol}
        \usepackage{lipsum}
        \usepackage{hyperref}
        \usepackage{libertine}
        \usepackage{ctex}         % 支持中文
        \pagestyle{empty}
        \setlength{\multicolsep}{2pt plus 1.0pt minus 0.75pt}% 50% of original values
        \setlength{\columnsep}{3em}
    number-sections: False # 取消自动编号

# quarto render resume.qmd --to pdf --output-dir Documents
  
---
<!-- TITLE -->
\begin{huge}\begin{center}{\bf 陈宇轩}\end{center}\end{huge}

<!-- CONTACT INFO -->
\begin{center}电子邮箱: cyxnbnb@bu.edu ∙ cyxnbnbnb@gmail.com \\
联系方式: +1 8572564713 ∙ +86 13957992893 \\
个人网站: \href{https://cyxnbnbnb.github.io/}{cyxnbnbnb.github.io} 
\end{center}
\vspace{15pt}

<!-- EDUCATION: 1ST BULLET -->
\begin{large}
  {\bf 教育经历}
  \vspace{3pt}
  \hrule
  \begin{multicols}{2}
    \begin{flushleft}{\bf 浙江工业大学}\end{flushleft}
    \begin{flushright}2020.9 - 2024.6\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}理学学士\hspace{1cm}数学与应用数学\end{flushleft}
  \end{multicols}
  \vspace{-0.20cm}
\end{large}
**相关课程**: 数学分析、高等代数、空间解析几何、常微分方程、随机过程、近世代数、实变函数、运筹学、最优化方法、时间序列分析、概率论与数理统计、复变函数与积分变换、数值计算、数据分析与R语言、数学模型、金融数学<br>
  \begin{multicols}{2}
    \begin{flushleft}{\bf * 浙江工业大学数学建模竞赛三等奖}\end{flushleft}
    \begin{flushright}2022.5\end{flushright}
  \end{multicols}
    \begin{multicols}{2}
    \begin{flushleft}{\bf * 浙江省第十届大学生广告创意竞赛优秀奖}\end{flushleft}
    \begin{flushright}2022.7\end{flushright}
  \end{multicols}
    \begin{multicols}{2}
    \begin{flushleft}{\bf * 第14届全国大学生广告艺术大赛优秀奖}\end{flushleft}
    \begin{flushright}2022.7\end{flushright}
  \end{multicols}


\vspace{0.2cm}

<!-- EDUCATION: 2ND BULLET -->
\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}{\bf 哥伦比亚大学}\end{flushleft}
    \begin{flushright}2023.7 – 2023.8\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \parbox{1.4\linewidth}{\textbf{Value Investment Techniques}: 价值投资技术:CFA证书中高级估值模型应用及探索研究}
  \end{multicols}
  \vspace{-0.10cm}
\end{large}

\vspace{1.5pt}

* 参与关于价值投资技术及其相关估值模型的应用及探索研究。主要针对四支美股：微软 (MSFT)、苹果 (AAPL)、辉瑞 (PFE)和 默克 (MRK) ，对他们在2019至2022年间息税前利润/总营收、年回报率与每股收益(EPS)等数据进行分析处理；
* 使用Pearson相关系数讨论各项数据的相关性，并使用函数拟合绘制图像，探究各个指标对估值的影响以及在估值模型中的应用。

\vspace{0.2cm}

<!-- EDUCATION: 3ND BULLET -->
\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}{\bf 波士顿大学}\end{flushleft}
    \begin{flushright}2024.9 - 2025.8\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}硕士\hspace{1cm}应用商业分析\end{flushleft}
  \end{multicols}
  \vspace{-0.20cm}
\end{large}

**相关课程**: 商业分析基础、运营管理、金融概念、定量与定性决策、企业风险分析、营销分析、商业网络分析、商业分析数据挖掘、投资分析与投资组合管理、金融定量方法

\vspace{1.5pt}




<!-- EXPERIENCE : 1ST BULLET-->
\begin{large}{\bf 实习经历}
  \vspace{3pt}
  \hrule
  \begin{multicols}{2}
  \parbox{1.4\linewidth}{\bf 杭州谦和明德股权投资有限公司}
    \begin{flushright}2021.8 - 2021.9\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{投资助理}\end{flushleft}
    \begin{flushright}  \end{flushright}\end
  {multicols}
\end{large}
\vspace{-0.16cm}
* 协助调研整理2015年至2021年在纳斯达克和纽交所IPO上市企业共206家的招股说明书、券商、上市当天首发价格和收盘价格、市值、审计公司及法律顾问等相关信息，作为公司的信息资源，为其他企业策划IPO上市时寻找相似案例作为借鉴，并作为行业研究报告成为投资方向的分析资源，寻找行业赛道头部企业进行投资；
* 负责中信建投期货和大陆期货共四支期货的交易风控工作，观察持仓方向、开仓均价以及逐笔浮盈等信息，通过观测走势曲线和图表分析进行风险监测，提供期货交易的信息，使用文华财经根据交易信息进行期货买卖操作，并汇总总浮盈比例及预设风险敞口等制作收盘报告和交易报表。

\vspace{7pt}

<!-- EXPERIENCE : 2ND BULLET -->
\begin{large}
  \begin{multicols}{2}
    \parbox{1.4\linewidth}{\bf 国家税务总局金华市金东区税务局}
    \begin{flushright}2021.12 - 2022.1\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{纳税服务岗、办公室综合岗}\end{flushleft}
    \begin{flushright}  \end{flushright}\end
  {multicols}
\end{large}
\vspace{-0.16cm}
* 组织、协调和指导各税种、各环节的纳税服务工作，指导、辅助纳税人办理税务登记、申报纳税、发票领用、验旧、认证代开等日常涉税业务；
* 负责后勤事务，公文处理，文件起草，工作督办，宣传报道等工作；
* 使用金税三期与浙江省电子税务局，核查纳税人税务收取情况及行业税收信息，对税务数据进行数据分析收集并做整理汇总。

\vspace{7pt}

<!-- EXPERIENCE : 3RD BULLET -->
\begin{large}
  \begin{multicols}{2}
    \parbox{1.4\linewidth}{\bf 浙江金控投资管理有限公司}
    \begin{flushright}2024.4 - 2024.7\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{财务部助理}\end{flushleft}
    \begin{flushright}  \end{flushright}\end
  {multicols}
\end{large}
\vspace{-0.16cm}
* 参与深圳西斯特科技有限公司财务尽职调查与投资决策会议；
* 参与嘉兴武岳峰-鼎峰上绍院基金尽职调查报告；
* 参与常春藤基金浙江科创母基金尽职调查及出具投资建议书工作；
* 参与力合基金浙江科创母基金尽职调查及出具浙江省科创母基金参股广西力合中恒医药投资合伙企业（有限合伙）之投资建议书；
* 参与东方嘉富基金财务尽职调查约访；
* 参与格创通信（浙江）有限公司财务尽职调查访谈；
* 协助建立基于DCF（Discounted Cash Flow，现金流折现）的企业估值模型。

\vspace{7pt}




<!--Research Projects : 1ST BULLET -->
\begin{large}{\bf Research Projects}
  \vspace{3pt}
  \hrule
  \begin{multicols}{2}
  \parbox{1.6\linewidth}{\bf Predictive Analysis and Solution for Medical and Pension Security in Changzhou Using Regression Analysis}
    \begin{flushright}Jul. 2022\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Programmer}\end{flushleft}
    \begin{flushright}  \end{flushright}\end
  {multicols}
\end{large}
\vspace{-0.16cm}
* **Description**: This project focuses on predicting and addressing medical and pension security issues in Changzhou. The aim is to allocate city resources more efficiently based on the forecasted medical and pension security needs, providing high-quality medical and pension services to the public and building a more comprehensive social security service system.

\vspace{7pt}

<!-- Research Projects : 2ND BULLET -->
\begin{large}
  \begin{multicols}{2}
  \parbox{1.6\linewidth}{\bf Research on Quality Control Problems in Ore Processing Based on Multiple Linear Regression}
    \begin{flushright}Jul. 2022\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Programmer}\end{flushleft}
    \begin{flushright}  \end{flushright}\end
  {multicols}
\end{large}
\vspace{-0.16cm}
* **Description**: This project aims to optimize the problems associated with low resource recovery rates and unstable product quality in ore processing plants. By improving the quality of ore processing, the industry can save non-renewable mineral resources and energy consumption, contributing to environmental sustainability.

<!-- Research Projects : 3RD BULLET -->
\begin{large}
  \begin{multicols}{2}
  \parbox{1.6\linewidth}{\bf Research on Sorting System Optimization Based on the Greedy Algorithm}
    \begin{flushright}Aug. 2022\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Programmer}\end{flushleft}
    \begin{flushright}  \end{flushright}\end
  {multicols}
\end{large}
\vspace{-0.16cm}
* **Description**: This project focuses on improving the efficiency of the sorting process in the context of e-commerce and parcel delivery. It addresses order batching, item placement, and task assignment to enhance the overall performance of distribution centers, ultimately boosting the competitiveness of e-commerce companies.

<!-- Research Projects : 4TH BULLET -->
\begin{large}
  \begin{multicols}{2}
  \parbox{1.6\linewidth}{\bf Mobile Communication Network Site Planning and Regional Clustering Problem Based on Multi-Objective Programming Models}
    \begin{flushright}Aug. 2022\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Programmer}\end{flushleft}
    \begin{flushright}  \end{flushright}\end
  {multicols}
\end{large}
\vspace{-0.16cm}
* **Description**: This project deals with the complex issue of planning mobile communication network sites and clusters, considering the evolving technology and increasing demand for advanced communication services. The objective is to optimize the deployment of new base stations and types while minimizing costs and improving coverage.




<!-- AWARDS -->
\begin{large}{\bf Awards}
  \vspace{3pt}
  \hrule
\end{large}
* Third Prize in Zhejiang University of Technology Mathematical Modeling Competition in May 2022
* Excellent Prize in the 10th Zhejiang Province University Student Advertising Creative Competition in July 2022
* Excellent Prize in the 14th National University Student Advertising Art Competition in July 2022



<!-- Skills -->
\begin{large}{\bf Skills}
  \vspace{3pt}
  \hrule
\end{large}
**Technical Skills**: Microsoft Word, PowerPoint, Excel, MATLAB, C, Python, R, SPSS, Statistics