---
format: 
  pdf: 
    documentclass: article
    geometry:
      - top=10mm
      - left=15mm
      - right=15mm
      - bottom=5mm
      - heightrounded
    fontfamily: libertine
    colorlinks: true
    fontsize: '16'
    include-in-header: 
      text: |
        \usepackage{multicol}
        \usepackage{lipsum}
        \usepackage{hyperref}
        \usepackage{libertine}
        \pagestyle{empty}
        \setlength{\multicolsep}{2pt plus 1.0pt minus 0.75pt}% 50% of original values
        \setlength{\columnsep}{3em}
    number-sections: False # 取消自动编号

# quarto render resume.qmd --to pdf --output-dir Documents
  
---
<!-- TITLE -->
\begin{huge}\begin{center}{\bf Yuxuan Chen}\end{center}\end{huge}

<!-- CONTACT INFO -->
\begin{center}Email: cyxnbnb@bu.edu ∙ cyxnbnbnb@gmail.com \\
Phone: +1 8572564713 ∙ +86 13957992893 \\
Address:  Apt 12, 5 Walbridge St., Boston, MA \\
Link: \href{https://cyxnbnbnb.github.io/}{cyxnbnbnb.github.io} \\
Home Page: \href{https://github.com/CYXNBNBNB}{github.com/CYXNBNBNB}
\end{center}
\vspace{15pt}





<!-- SKILLS -->
\begin{large}{\bf SKILLS}
  \vspace{3pt}
  \hrule
\end{large}
* **Technical Skills**: Python, R, MATLAB, SQL, C, SPSS, Stata, Microsoft Word, PowerPoint, Excel

\vspace{0.2cm}







<!-- EDUCATION: Boston University -->
\begin{large}
  {\bf EDUCATION}
  \vspace{3pt}
  \hrule
  \begin{multicols}{2}
    \begin{flushleft}{\bf Boston University}\end{flushleft}
    \begin{flushright}Sep. 2024 - Aug. 2025\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}MS in Applied Business Analytics\end{flushleft}
  \end{multicols}
  \vspace{-0.20cm}
\end{large}

**Relevant Courses**: Business Analytics Foundations, Operations Management, Financial Concepts, Quantitative and Qualitative Decision Making, Enterprise Risk Analytics, Marketing Analytics, Web Analytics for Business, Data Mining for Business Analytics, Investment Analysis and Portfolio Management, Quantitative Methods for Finance.

\vspace{2pt}


<!-- EDUCATION: ZJUT -->
\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}{\bf Zhejiang University of Technology}\end{flushleft}
    \begin{flushright}Sep. 2020 - Jun. 2024\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}BS in Mathematics and Applied Mathematics\end{flushleft}
  \end{multicols}
  \vspace{-0.20cm}
\end{large}
**Relevant Courses**: Mathematical Analysis, Advanced Algebra, Analytical Geometry, Ordinary Differential Equations, Probability Theory, Operations Research, Optimization Methods, Time Series Analysis, Complex Variables and Integral Transform, Numerical Computation, Data Analysis with R, Mathematical Modeling, Financial Mathematics.

**Awards**

* Third Prize in Zhejiang University of Technology Mathematical Modeling Competition in May 2022
* Excellent Prize in the 10th Zhejiang Province University Student Advertising Creative Competition in July 2022
* Excellent Prize in the 14th National University Student Advertising Art Competition in July 2022

\vspace{0.2cm}




<!--Research Projects : Boston University 1St -->
\begin{large}{\bf RESEARCH PROJECTS}
  \vspace{3pt}
  \hrule
    \begin{flushleft}{\bf | Boston University}\end{flushleft}
  \begin{multicols}{2}
    \parbox{1.4\linewidth}{\textbf {Domestic(U.S.) and International Equity Portfolio research}}
    \begin{flushright}May. 2025 – Jun. 2025\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
\end{large}

\vspace{1.5pt}

**Domestic Equity Portfolio Project**

* Constructed a diversified 3-stock U.S. equity portfolio based on historical return and sectoral diversification from 2000 to 2025, using S&P500 and Dow30 as benchmarks.
* Performed time-series and cross-sectional analysis of monthly holding period yields (HPYs), including mean returns, volatility, Sharpe ratio, and systematic risk (Beta).
* Estimated expected returns using both CAPM and Dividend Discount Model (DDM) for dividend-paying stocks.
* Visualized portfolio growth and comparative performance using Excel-based index plots, efficient frontiers, and return-risk plots.

**International Equity Portfolio Project**

* Designed a 6-country international ETF portfolio (including U.S., China, and four additional markets), incorporating both developed and emerging economies to ensure geographical and structural diversification.
* Computed returns in USD as the Reporting Currency, accounting for foreign exchange rates and using aligned monthly data from 2000 to 2025.
* Conducted return analysis, risk assessment, and correlation studies across markets to evaluate diversification benefits.
* Created and interpreted capital base index (CBI) plots, correlation matrices, and international portfolio efficient frontiers.

**Repository**: [AD717-Domestic_n_International_Equity_Portfolio_Project](https://github.com/CYXNBNBNB/AD717-Domestic_n_International_Equity_Portfolio_Project.git)

\vspace{0.2cm}



<!--Research Projects : Boston University 2ND -->
\begin{large}
  \begin{multicols}{2}
  \parbox{1.6\linewidth}{\textbf{Data-Driven Career Analysis}: Evaluating Personal Job Market Prospects in 2024}
    \begin{flushright}Feb. 2025 – May. 2025\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
\end{large}

\vspace{1.5pt}

* This study explores the differences in compensation between AI and non-AI occupations, the geographic distribution of high-paying AI and traditional roles, the salary comparison between remote and on-site jobs, the fastest-growing industries in terms of wages in 2024, and the key beneficiaries of the rise of AI. Using data from Lightcast and external labor market sources, it focuses on pay disparities across disciplines and examines how job seekers can effectively position themselves amid evolving hiring trends, compensation patterns, AI adoption, remote work, and gender-based employment dynamics.

* Using Exploratory Data Analysis (EDA), this study examines salary comparisons between remote and on-site jobs, regional salary distributions, the highest-paying occupations, and compensation differences between AI and non-AI roles. It also compares team skills with industry demands to conduct a Skill Gap Analysis, identifying areas where the team's capabilities may not align with market expectations.
* **Machine Learning (ML)**: Perform cluster analysis on the dataset using K-Means to explore how different job roles group into clusters based on salary, employment type, job duration, education level, remote options, state, and other categorical factors. Additionally, build a multiple linear regression model to predict salary.
* **Natural Language Processing (NLP) Approach**: Apply K-Means clustering to the TF-IDF features of job descriptions to divide them into four distinct clusters, and generate word clouds for each cluster for analysis. In addition, train two different classifiers—Naive Bayes and Support Vector Machine (SVM)—to predict the corresponding job cluster based on the TF-IDF features extracted from the job descriptions.

**Website**: [https://cyxnbnbnb.github.io/ad688-employability-sp25A1-group6/](https://cyxnbnbnb.github.io/ad688-employability-sp25A1-group6/)

**Repository**: [https://github.com/CYXNBNBNB/ad688-employability-sp25A1-group6](https://github.com/CYXNBNBNB/ad688-employability-sp25A1-group6)


\vspace{0.2cm}


<!--Research Projects : Boston University 3RD -->
\begin{large}
  \begin{multicols}{2}
  \parbox{1.6\linewidth}{\textbf{Lobster Land: Cruise Industry Expansion Consulting}}
    \begin{flushright}Feb. 2025 – May. 2025\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
\end{large}

\vspace{1.5pt}

Worked in a consulting team hired by “Lobster Land” to evaluate potential expansion into the cruise industry. Leveraged analytics and business insights to provide strategic recommendations across multiple domains: 

* **Market Analysis & Segmentation**: Clustered Caribbean cruise-port data to define segments and recommend tailored itineraries and marketing.
* **Conjoint Analysis**: Used ratings-based conjoint modeling to identify the most appealing and cost-effective onboard experience bundles for overnight voyages; selected combinations within budget constraints.
* **Predictive Modeling**: Built a classification model to predict customer cancellation risk; translated model insights into actionable retention strategies.
* **Forecasting & A/B Testing**: Forecasted 2025 EPS for major cruise lines (Carnival & NCLH); performed A/B testing on cruise-themed marketing visuals to guide creative selection.
* **Strategic Case Analysis**: Developed a customer segmentation-based cruise product proposal inspired by Royal Caribbean's *Icon of the Seas*.

**Repository**: [https://github.com/CYXNBNBNB/AD654-Sp25A3-Project](https://github.com/CYXNBNBNB/AD654-Sp25A3-Project)

\vspace{0.2cm}



<!--Research Projects : Columbia University -->
\begin{large}{\bf RESEARCH PROJECTS}
  \vspace{3pt}
  \hrule
    \begin{flushleft}{\bf | Columbia University}\end{flushleft}
  \begin{multicols}{2}
    \parbox{1.4\linewidth}{\textbf {Value Investment Techniques}: Advanced Application and Exploration Research of Valuation Models in CFA Certification}
    \begin{flushright}Jul. 2023 – Sep. 2023\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
\end{large}

\vspace{1.5pt}


* Engaged in research on the application and exploration of value investment techniques and related valuation models. Primarily focused on four US stocks: Microsoft (MSFT), Apple (AAPL), Pfizer (PFE), and Merck (MRK). Analyzed and processed data regarding their Earnings Before Interest and Taxes (EBIT) to Total Revenue, annual return rates, and Earnings Per Share (EPS) from 2019 to 2022.
* Utilized Pearson correlation coefficients to discuss the correlations among the data and employed function fitting to generate graphs, exploring the impact of various indicators on valuation and their application within valuation models.

\vspace{0.2cm}

<!-- Research Projects : ZJUT 1ST -->
\begin{large}
  \begin{flushleft}{\bf | Zhejiang University of Technology}\end{flushleft}
  \begin{multicols}{2}
  \parbox{1.6\linewidth}{\textbf{Research on Sorting System Optimization Based on the Greedy Algorithm}}
    \begin{flushright}Aug. 2022\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Programmer}\end{flushleft}
    \begin{flushright}  \end{flushright}\end
  {multicols}
\end{large}
\vspace{-0.16cm}
* **Description**: This project focuses on improving the efficiency of the sorting process in the context of e-commerce and parcel delivery. It addresses order batching, item placement, and task assignment to enhance the overall performance of distribution centers, ultimately boosting the competitiveness of e-commerce companies.

\vspace{7pt}

<!-- Research Projects : ZJUT 2ND -->
\begin{large}
  \begin{multicols}{2}
  \parbox{1.6\linewidth}{\textbf{Mobile Communication Network Site Planning and Regional Clustering Problem Based on Multi-Objective Programming Models}}
    \begin{flushright}Aug. 2022\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Programmer}\end{flushleft}
    \begin{flushright}  \end{flushright}\end
  {multicols}
\end{large}
\vspace{-0.16cm}
* **Description**: This project deals with the complex issue of planning mobile communication network sites and clusters, considering the evolving technology and increasing demand for advanced communication services. The objective is to optimize the deployment of new base stations and types while minimizing costs and improving coverage.

\vspace{7pt}

<!-- Research Projects : ZJUT 3RD -->
\begin{large}
  \begin{multicols}{2}
  \parbox{1.6\linewidth}{\textbf{Predictive Analysis and Solution for Medical and Pension Security in Changzhou Using Regression Analysis}}
    \begin{flushright}Jul. 2022\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Programmer}\end{flushleft}
    \begin{flushright}  \end{flushright}\end
  {multicols}
\end{large}
\vspace{-0.16cm}
* **Description**: This project focuses on predicting and addressing medical and pension security issues in Changzhou. The aim is to allocate city resources more efficiently based on the forecasted medical and pension security needs, providing high-quality medical and pension services to the public and building a more comprehensive social security service system.

\vspace{7pt}

<!-- Research Projects : ZJUT 4TH -->
\begin{large}
  \begin{multicols}{2}
  \parbox{1.6\linewidth}{\textbf{Research on Quality Control Problems in Ore Processing Based on Multiple Linear Regression}}
    \begin{flushright}Jul. 2022\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Programmer}\end{flushleft}
    \begin{flushright}  \end{flushright}\end
  {multicols}
\end{large}
\vspace{-0.16cm}
* **Description**: This project aims to optimize the problems associated with low resource recovery rates and unstable product quality in ore processing plants. By improving the quality of ore processing, the industry can save non-renewable mineral resources and energy consumption, contributing to environmental sustainability.

\vspace{7pt}






<!-- EXPERIENCE : 1ST BULLET -->
\begin{large}{\bf EXPERIENCE}
  \vspace{3pt}
  \hrule
  \begin{multicols}{2}
    \parbox{1.4\linewidth}{\textbf{Zhejiang Jinkong Investment Management Co., Ltd.}}
    \begin{flushright}Apr. 2024 - Jul. 2024\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Finance Department Assistant}\end{flushleft}
    \begin{flushright}  \end{flushright}\end
  {multicols}
\end{large}
\vspace{-0.16cm}
* Participated in the financial due diligence and investment decision-making meetings of System Technology (Shenzhen) Co., Ltd.
* Participated in the due diligence report of Jiaxing Wuyuefeng-Dingfeng Shangshaoyuan Fund.
* Participated in the due diligence and issuance of investment proposals for Ivy Capital's Zhejiang Science and Innovation Master Fund.
* Participated in the due diligence investigation of Leaguer Fund's Zhejiang Science and Innovation Master Fund and issued an investment proposal for Zhejiang Science and Innovation Master Fund's participation in Guangxi Leaguer Zhongheng Pharmaceutical Investment Partnership (Limited Partnership).
* Participated in financial due diligence appointments for the Orient Renaissance Capital.
* Participated in financial due diligence interviews with Getech Communications (Zhejiang) Co.
* Assisted in building business valuation models based on DCF (Discounted Cash Flow).

\vspace{7pt}

<!-- EXPERIENCE : 2ND BULLET -->
\begin{large}
  \begin{multicols}{2}
    \parbox{1.4\linewidth}{\textbf{State Taxation Bureau Jindong District, Jinhua City}}
    \begin{flushright}Dec. 2021 - Jan. 2022\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Tax Service Officer and Office Assistant}\end{flushleft}
    \begin{flushright}  \end{flushright}\end
  {multicols}
\end{large}
\vspace{-0.16cm}
* Organized, coordinated, and guided tax services for various tax types and processes. Assisted taxpayers with tax registration, tax declaration, invoice issuance, verification, certification, and other daily tax-related tasks.
* Handled logistics affairs, document processing, drafting documents, work supervision, and publicity and reporting tasks.
* Used the Golden Tax Phase III system and Zhejiang Province Electronic Taxation Bureau for tax data verification, industry tax information collection, and data analysis.

\vspace{7pt}

<!-- EXPERIENCE : 3RD BULLET-->
\begin{large}
  \begin{multicols}{2}
  \parbox{1.4\linewidth}{\textbf{Hangzhou Qianhe Mingde Equity Investment Co., Ltd.}}
    \begin{flushright}Aug. 2021 - Sep. 2021\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Investment Assistant}\end{flushleft}
    \begin{flushright}  \end{flushright}\end
  {multicols}
\end{large}
\vspace{-0.16cm}
* Collected, researched, and organized information on 206 companies listed on NASDAQ and NYSE through IPOs from 2015 to 2021. This information included prospectuses, brokerage firms, IPO opening and closing prices, market capitalization, audit companies, and legal advisors. This data was used as a resource for planning IPOs for other companies and for industry research reports.
* Managed risk control for four futures including China Securities and Continental Futures. Monitored position directions, opening prices, and real-time profits and used trend analysis and chart analysis for risk monitoring. Provided information on futures trading and prepared closing and transaction reports.

\vspace{7pt}