project:
  type: website
  output-dir: ../docs  # 让 Quarto 输出到 docs 目录

website:
  title: "Yuxuan Chen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    tools:
      - icon: github
        menu:
          - text: Home Page
            href:  https://github.com/CYXNBNBNB
          - text: Source Code
            href:  https://github.com/CYXNBNBNB/cyxnbnbnb.github.io

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true




